version: "3.2"

services:
  backend:
    restart: always
    command : sh -c "python manage.py migrate && pytest &&
                     python manage.py runserver 0.0.0.0:8000"
    image: nahuelbarbieri/flight_booking_backend:v2
    ports:
      - "8000:8000"
      
  frontend:
    restart: always
    command : npm start
    image: nahuelbarbieri/flight_booking_frontend:v2
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
