# Generated by Django 4.0.3 on 2022-04-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField()),
                ('arriving_date', models.DateTimeField()),
                ('arriving_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_city', to='flight_booking.city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city', to='flight_booking.city')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.IntegerField()),
                ('is_first_class', models.BooleanField()),
                ('go_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_flight', to='flight_booking.flight')),
                ('round_flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_flight', to='flight_booking.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookings', models.ManyToManyField(to='flight_booking.flightbooking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
