# Generated by Django 4.0.3 on 2022-04-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arriving_date',
            new_name='arriving_datetime',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure_date',
            new_name='departure_datetime',
        ),
    ]
